language: node_js
node_js:
  - "4"
  - "5"
  - "6"
sudo: false
os: linux

before_script:
  - npm install -g gulp-cli
  - npm install

script:
  - npm test
  - gulp
  - git diff --quiet # make sure no files have changed
