language: node_js
node_js:
  - "4"
  - "5"
  - "6"
sudo: false
os: linux

before_script:
  - npm install

script:
  - npm test
  - npm run build
  - npm run after-travis "Make sure you regenerate HTML"

after_success:
  - bash <(curl -s https://codecov.io/bash)
